# 머신러닝 주요 라이브러리
- Numpy
- Pandas
- sckit-learn
- matplotlib 확인:pip list


## 1. Numpy  
넘파이 - ndarray 다차원 객체 빠르다

In [1]:
import numpy as np

In [129]:
## 연산자, 함수
a = np.array([1,2,3])
b = np.array([10,11,12])

In [136]:
a+b # np.add(a,b)
a**2 # ^ 는 xor연산
1^2 # 2진법 연산
int('1',2)^int('10',2) # 2진법 표현법

array([1, 4, 9], dtype=int32)

---

In [25]:
a = np.array([[1,2,3],[4,5,6]]) # 2차원

In [250]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3차원

In [249]:
b.ndim  # axis(축)수 반환
b.shape # shape
b.dtype
b.size # 크기 : len(b.ravel)과 같다, len(b)는 가장 겉의 크기

12

In [252]:
b.sum(axis=0) # b[:,n,m]
# b.sum(axis=1) # b[n,:,m]
# b.sum(axis=2) # b[n,m,:]

# b[:,0,0].sum()
# b.sum()

array([[ 8, 10, 12],
       [14, 16, 18]])

In [255]:
c = np.array(range(1,13))
b == b.reshape(2,2,-1) # b.reshape(2,2,3) 과 동일 -1은 자동으로 할당
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [294]:
b[-2] # - 뒤쪽부터 카운팅
b[:,1]==b[:,1:2]


array([[[ True,  True,  True],
        [False, False, False]],

       [[False, False, False],
        [ True,  True,  True]]])

In [311]:
test=b[:,1:2]
test2=b[:,1]
print(b)
print(test)
print(test2)
print(test.shape)
print(test2.reshape(2,1,3))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 4  5  6]]

 [[10 11 12]]]
[[ 4  5  6]
 [10 11 12]]
(2, 1, 3)
[[[ 4  5  6]]

 [[10 11 12]]]


In [299]:
b[:,1]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [293]:
a[[0,1]]==a[0:2]

array([ True,  True])

In [68]:
a[0][1]

2

In [69]:
a[0,1]

2

In [72]:
a.ravel() # 1차원 배열로

array([1, 2, 3, 4, 5, 6])

In [73]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
a.T # 전치행렬 Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

#### grayscale로 회색변환을 해주면 흑백이기에 2차원으로 변환  
----
#### axis에 대해서
- 2 dim : 밑 = 0, 옆 = 1
- 3 dim : 뒤/밑/옆 = 0,1,2

## 2. pandas
- Series: 1차원
- DataFrame: 2차원
- Panel: 3차원

In [79]:
import pandas as pd

In [80]:
a = pd.Series(['a','b','c'],index = [3,2,1])

In [214]:
test = {'Name':["a","kim","Jone"],'Location':["here","there","where"],'Age':[1,2,3]}

In [215]:
test_df = pd.DataFrame(test)

In [86]:
test_df[test_df.Age>1]

Name Location  Age
1   kim    there    2
2  Jone    where    3

In [115]:
test_df['Name'] # Series

0       a
1     kim
2    Jone
Name: Name, dtype: object

In [116]:
test_df[['Name']] # DataFrame

Name
0     a
1   kim
2  Jone

In [91]:
test_df[['Name','Location']][0:2]

Name Location
0    a     here
1  kim    there

In [117]:
test_df[0:2]

Name Location  Age
0    a     here    1
1  kim    there    2

In [113]:
test_df['Name'][1]

'kim'

In [191]:
test_df.iloc[0:1]

Name Location  Age
0    a     here    1

In [192]:
test_df.iloc[[0,2],[0,2]]

Name  Age
0     a    1
2  Jone    3

In [205]:
test_df.iloc[[0,1]]['Name']

0      a
1    kim
Name: Name, dtype: object

In [206]:
test_df.iloc[[0,1][1]]

Name          kim
Location    there
Age             2
Name: 1, dtype: object

In [203]:
test_df.loc[[0,2],'Name']

0       a
2    Jone
Name: Name, dtype: object

In [197]:
test_df.iloc[[0,1]]

Name Location  Age
0    a     here    1
1  kim    there    2

In [201]:
test_df.loc[0:1,'Name':'Age']

Name Location  Age
0    a     here    1
1  kim    there    2

In [217]:
# column 위치 바꾸기
test_df = pd.DataFrame(test_df,columns=('Name','Age','Location'))

In [222]:
df = test_df.reindex([1,2,3])
df

Name  Age Location
1   kim  2.0    there
2  Jone  3.0    where
3   NaN  NaN      NaN

In [220]:
test_df

Name  Age Location
0     a    1     here
1   kim    2    there
2  Jone    3    where

In [232]:
df['Hobby'] = ['book','work','haha']

In [233]:
df

Name  Age Location Hobby
1   kim  2.0    there  book
2  Jone  3.0    where  work
3   NaN  NaN      NaN  haha